icons-enabled=no
font=JetBrainsMono:size=16
lines=8
width=30
horizontal-pad=16

# keyboard-focus=on-demand
# exit-on-keyboard-focus-loss=no
# anchor=top-right

[colors]
background=faf2ebff
selection=e6e4d9ff
prompt=000000ff
text=000000dd
match=af3029dd
selection-text=000000dd
selection-match=000000dd
input=000000dd

[border]
radius=0

[key-bindings]
execute-or-next=none
insert-selected=Tab


